[package]
name = "github-scbot"
version = "0.1.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1"
actix-service = "1"
actix-web = "3"
chrono = { version = "0.4.19", features = ["serde"] }
color-eyre = "0.5"
derive_more = "0.99.11"
diesel = { version = "1.4", features = ["sqlite", "chrono", "r2d2"] }
diesel_migrations = "1.4"
dotenv = "0.15"
env_logger = "0.8"
eyre = "0.6"
futures = "0.3"
hex = "0.4"
log = "0.4"
octocrab = "0.8"
once_cell = "1" 
r2d2 = "0.8"
r2d2-diesel = "1"
rust-crypto = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.5"