[package]
name = "github-scbot"
version = "0.1.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-service = "1"
actix-web = "3"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4", features = ["sqlite", "chrono"] }
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3"
hex = "0.4"
log = "0.4"
octocrab = "0.8"
rust-crypto = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.5"