[package]
name = "github-scbot-types"
version = "0.9.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0"
serde = { version = "1", features = ["derive"] }
serde_plain = "0.3.0"
