[package]
name = "github-scbot-types"
version = "0.10.2"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
github-scbot-libs = { path = "../github_scbot_libs" }
thiserror = "1.0"
serde = { version = "1", features = ["derive"] }
