[package]
name = "github-scbot-ghapi"
version = "0.21.2"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

[dependencies]
github-scbot-conf = { path = "../github_scbot_conf" }
github-scbot-crypto = { path = "../github_scbot_crypto" }
github-scbot-types = { path = "../github_scbot_types" }
github-scbot-utils = { path = "../github_scbot_utils" }

async-trait = "0.1.50"
chrono = { version = "0.4.19", features = ["serde"] }
futures-util = "0.3.21"
heck = "0.3.2"
http = "0.2"
mockall = "0.11.0"
rand = "0.8"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "0.3.0"
snafu = "0.7.1"
tracing = "0.1"

[dev-dependencies]
actix-rt = "2"
maplit = "1.0.2"
