[package]
name = "github-scbot-database-pg"
version = "0.23.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
github-scbot-domain-models = { path = "../github-scbot-domain-models" }
github-scbot-database-interface = { path = "../github-scbot-database-interface" }
github-scbot-core = { path = "../github-scbot-core" }
async-trait = "0.1.56"
sqlx = { version = "0.6.0", features = ["runtime-actix-native-tls", "postgres"] }
tracing = "0.1.35"

[dev-dependencies]
pretty_assertions = "1.2.1"
actix-rt = "2.7.0"
