[package]
name = "sentry-actix"
version = "0.25.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
description = """
Sentry client extension for actix-web 4.
"""
edition = "2021"

[dependencies]
actix-web = { version = "4", default-features = false }
futures-util = { version = "0.3.5", default-features = false }
sentry-core = { version = "0.25.0", features = ["client"] }
sentry-eyre = { path = "../sentry-eyre", optional = true }
serde_json = { version = "1", optional = true }

[features]
eyre = ["sentry-eyre", "serde_json"]
