[package]
name = "github-scbot-conf"
version = "0.9.2"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
jsonwebtoken = "7"
sentry = "0.21"
sentry-eyre = { path = "../sentry_eyre" }
stable-eyre = "0.2"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
