[package]
name = "github-scbot-conf"
version = "0.11.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
github-scbot-libs = { path = "../github_scbot_libs" }
sentry-eyre = { path = "../sentry_eyre" }
thiserror = "1.0"
