[package]
name = "prbot-ghapi-interface"
version = "0.0.0"
authors = ["Denis BOURGE <Srynetix@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prbot-config = { path = "../prbot-config" }

async-trait = { workspace = true }
heck = "0.5.0"
serde = { workspace = true }
serde_plain = "1.0.2"
smart-default = "0.7.1"
thiserror = { workspace = true }
time = { workspace = true }

mockall = { workspace = true, optional = true }

[features]
default = []
testkit = ["mockall"]
