[package]
name = "github-scbot-domain"
version = "0.23.0-dev"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

[dependencies]
github-scbot-core = { path = "../github-scbot-core" }
github-scbot-database = { path = "../github-scbot-database" }
github-scbot-ghapi = { path = "../github-scbot-ghapi" }
github-scbot-redis = { path = "../github-scbot-redis" }

async-trait = "0.1.56"
regex = "1.6.0"
smart-default = "0.6.0"
tracing = "0.1.35"
thiserror = "1.0.37"

[dev-dependencies]
actix-rt = "2.7.0"
futures-util = "0.3.21"
maplit = "1.0.2"
mockall = "0.11.2"
pretty_assertions = "1.2.1"
