version: "3"

services:
  server:
    image: prbot:0.25.0
    env_file: ../.env
    environment:
      BOT_DATABASE_PG_URL: postgresql://user:pass@postgres:5432/bot
      BOT_LOCK_REDIS_ADDRESS: redis:6379
      BOT_SERVER_BIND_IP: 0.0.0.0
      RUST_LOG: info,prbot=debug
    ports:
      - 8008:8008

  postgres:
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bot
    command: "-c max_connections=200"

  redis:
    image: redis:alpine

volumes:
  postgres-data:
