[package]
name = "prbot-crypto"
version = "0.0.0"
authors = ["Denis BOURGE <Srynetix@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
hmac = "0.12.1"
jsonwebtoken = "9.3.0"
rand = { workspace = true }
rsa = "0.9.6"
sha2 = "0.10.8"
serde = { workspace = true }
thiserror = { workspace = true }
