[package]
name = "prbot-ghapi-github"
version = "0.0.0"
authors = ["Denis BOURGE <Srynetix@users.noreply.github.com>"]
edition = "2021"

[dependencies]
prbot-config = { path = "../prbot-config" }
prbot-crypto = { path = "../prbot-crypto" }
prbot-ghapi-interface = { path = "../prbot-ghapi-interface" }

async-trait = { workspace = true }
backoff = { version = "0.4.0", features = ["tokio"] }
http = "1.1.0"
reqwest = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
lazy_static = { workspace = true }

[dev-dependencies]
prbot-ghapi-interface = { path = "../prbot-ghapi-interface", features = ["testkit"] }
