[package]
name = "prbot"
version = "0.25.1"
authors = ["Denis BOURGE <Srynetix@users.noreply.github.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
prbot-config = { path = "../prbot-config" }
prbot-crypto = { path = "../prbot-crypto" }
prbot-database-interface = { path = "../prbot-database-interface" }
prbot-database-pg = { path = "../prbot-database-pg" }
prbot-database-memory = { path = "../prbot-database-memory" }
prbot-core = { path = "../prbot-core" }
prbot-models = { path = "../prbot-models" }
prbot-ghapi-interface = { path = "../prbot-ghapi-interface" }
prbot-ghapi-null = { path = "../prbot-ghapi-null" }
prbot-lock-interface = { path = "../prbot-lock-interface" }
prbot-lock-null = { path = "../prbot-lock-null" }
prbot-logging = { path = "../prbot-logging" }
prbot-sentry = { path = "../prbot-sentry" }
prbot-server = { path = "../prbot-server" }
prbot-tui = { path = "../prbot-tui" }

actix-rt = "2.9.0"
anyhow = { version = "1.0", features = ["backtrace"] }
async-trait = { workspace = true }
clap = { workspace = true }
dotenv = "0.15.0"
shaku = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
shadow-rs = "0.27.1"

[dev-dependencies]
prbot-lock-interface = { path = "../prbot-lock-interface", features = ["testkit"] }
prbot-ghapi-interface = { path = "../prbot-ghapi-interface", features = ["testkit"] }

[build-dependencies]
shadow-rs = "0.27.1"
