[package]
name = "github-scbot-tui"
version = "0.15.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
github-scbot-conf = { path = "../github_scbot_conf" }
github-scbot-database = { path = "../github_scbot_database" }
github-scbot-types = { path = "../github_scbot_types" }

termion = "1.5.5"
thiserror = "1.0"
tui = "0.13"
