[package]
name = "github-scbot-tui"
version = "0.10.2"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
github-scbot-conf = { path = "../github_scbot_conf" }
github-scbot-database = { path = "../github_scbot_database" }
github-scbot-types = { path = "../github_scbot_types" }
github-scbot-libs = { path = "../github_scbot_libs" }
thiserror = "1.0"
