[package]
name = "github-scbot-tui"
version = "0.9.4"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
github-scbot-conf = { path = "../github_scbot_conf" }
github-scbot-database = { path = "../github_scbot_database" }
github-scbot-types = { path = "../github_scbot_types" }
thiserror = "1.0"
termion = "1.5.5"
tui = "0.13"
