[package]
name = "github-scbot-tui"
version = "0.19.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

[dependencies]
github-scbot-conf = { path = "../github_scbot_conf" }
github-scbot-database2 = { path = "../github_scbot_database2" }
github-scbot-types = { path = "../github_scbot_types" }
thiserror = "1.0"

[target.'cfg(unix)'.dependencies]
termion = "1.5.5"
tui = "0.13"
