[package]
name = "github-scbot-redis"
version = "0.10.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
actix-redis = "0.9.2"
async-trait = "0.1.50"
redis-async = "0.6.3"
thiserror = "1.0.25"

[dev-dependencies]
actix-rt = "1"
