[package]
name = "github-scbot-redis"
version = "0.21.1"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
github-scbot-utils = { path = "../github_scbot_utils" }

actix = "0.12.0"
actix-redis = "0.11.0"
async-trait = "0.1.50"
mockall = "0.11.0"
redis-async = "0.12.1"
thiserror = "1.0.25"
tracing = "0.1"

[dev-dependencies]
actix-rt = "2.7.0"
