[package]
name = "github-scbot-redis"
version = "0.11.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
github-scbot-utils = { path = "../github_scbot_utils" }
github-scbot-libs = { path = "../github_scbot_libs" }
thiserror = "1.0.25"

[dev-dependencies]
actix-rt = "1"
