[package]
name = "github-scbot-cli"
version = "0.22.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

[dependencies]
github-scbot-core = { path = "../github-scbot-core" }
github-scbot-ghapi = { path = "../github-scbot-ghapi" }
github-scbot-database2 = { path = "../github-scbot-database2" }
github-scbot-logic = { path = "../github-scbot-logic" }
github-scbot-server = { path = "../github-scbot-server" }
github-scbot-tui = { path = "../github-scbot-tui" }
github-scbot-redis = { path = "../github-scbot-redis" }

actix-rt = "2"
async-trait = "0.1.50"
argh = "0.1.6"
dialoguer = "0.8.0"
owo-colors = "1.3.0"
tokio = { version = "1.17.0", features = ["full"] }
snafu = { version = "0.7.1", features = ["backtrace", "backtraces-impl-backtrace-crate"] }
clap = { version = "3.1.18", features = ["derive"] }

[dev-dependencies]
indoc = "1.0.4"
