[package]
name = "github-scbot-tui"
version = "0.23.0-rc1"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

[dependencies]
github-scbot-core = { path = "../github-scbot-core" }
github-scbot-database = { path = "../github-scbot-database" }
crossterm = "0.25.0"
snafu = "0.7.1"
tui = "0.19.0"
