[package]
name = "github-scbot-tui"
version = "0.22.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

[dependencies]
github-scbot-core = { path = "../github-scbot-core" }
github-scbot-database = { path = "../github-scbot-database" }
snafu = "0.7.1"

[target.'cfg(unix)'.dependencies]
termion = "1.5.6"
tui = { version = "0.18.0", features = ["termion"] }
