[package]
name = "github-scbot-cli"
version = "0.11.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
github-scbot-api = { path = "../github_scbot_api" }
github-scbot-conf = { path = "../github_scbot_conf" }
github-scbot-database = { path = "../github_scbot_database" }
github-scbot-logic = { path = "../github_scbot_logic" }
github-scbot-server = { path = "../github_scbot_server" }
github-scbot-tui = { path = "../github_scbot_tui" }
github-scbot-redis = { path = "../github_scbot_redis" }
github-scbot-types = { path = "../github_scbot_types" }
github-scbot-libs = { path = "../github_scbot_libs" }
sentry-eyre = { path = "../sentry_eyre" }
structopt = "0.3"
thiserror = "1.0"

[dev-dependencies]
actix-rt = "1"
