//! API constants

pub const ENV_GITHUB_API_TOKEN: &str = "BOT_GITHUB_API_TOKEN";
pub const ENV_DISABLE_WELCOME_COMMENTS: &str = "BOT_DISABLE_WELCOME_COMMENTS";
pub const ENV_API_DEBUG_MODE: &str = "BOT_API_DEBUG_MODE";
