[package]
name = "github-scbot-server"
version = "0.22.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

[dependencies]
github-scbot-core = { path = "../github-scbot-core" }
github-scbot-ghapi = { path = "../github-scbot-ghapi" }
github-scbot-database2 = { path = "../github-scbot-database2" }
github-scbot-logic = { path = "../github-scbot-logic" }
github-scbot-redis = { path = "../github-scbot-redis" }

actix-cors = "0.6.1"
actix-http = "3.0.4"
actix-web = "4.0.1"
actix-web-httpauth = "0.6.0"
actix-web-prom = "0.6.0"
async-trait = "0.1.50"
futures = "0.3"
hex = "0.4"
regex = "1.4"
rust-crypto = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
snafu = "0.7.1"
tracing = "0.1"
tracing-actix-web = "0.5.1"
prometheus = { version = "0.13.0", features = ["process"] }
lazy_static = "1.4.0"

[dev-dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
pretty_assertions = "0.7.2"
