[package]
name = "github-scbot-libs"
version = "0.11.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
actix = "0.10.0"
actix-cors = "0.5"
actix-http = "2.2"
actix-redis = "0.9.2"
actix-rt = "1"
actix-service = "1"
actix-web = "3"
actix-web-httpauth = "0.5"
async-trait = "0.1.50"
thiserror = "1.0.25"
chrono = { version = "0.4.19", features = ["serde"] }
dialoguer = "0.8.0"
dotenv = "0.15"
futures = "0.3"
heck = "0.3.2"
hex = "0.4"
http = "0.2"
jsonwebtoken = "7"
octocrab = "0.8"
openssl = "0.10"
owo-colors = "1.2"
r2d2 = "0.8"
rand = "0.8"
redis-async = "0.6.3"
regex = "1.4"
reqwest = "0.10.9"
rust-crypto = "0.2"
sentry = "0.21"
sentry-core = "0.21"
serde_json = "1"
serde_plain = "0.3.0"
smart-default = "0.6.0"
stable-eyre = "0.2"
termion = "1.5.5"
tokio-diesel = "0.3.0"
tracing = "0.1"
tracing-subscriber = "0.2"
tui = "0.13"
