[package]
name = "github-scbot-crypto"
version = "0.17.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
jsonwebtoken = "7"
rand = "0.8.4"
rsa = "0.5.0"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
