[package]
name = "github-scbot-crypto"
version = "0.1.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
jsonwebtoken = "7"
openssl = "0.10.32"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
