[package]
name = "github-scbot-crypto"
version = "0.12.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
github-scbot-libs = { path = "../github_scbot_libs" }
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
