[package]
name = "github-scbot-crypto"
version = "0.22.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

[dependencies]
jsonwebtoken = "7"
rand = "0.8.4"
rsa = "0.5.0"
serde = { version = "1", features = ["derive"] }
snafu = "0.7.1"
