[package]
name = "github-scbot-server"
version = "0.14.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
github-scbot-ghapi = { path = "../github_scbot_ghapi" }
github-scbot-conf = { path = "../github_scbot_conf" }
github-scbot-crypto = { path = "../github_scbot_crypto" }
github-scbot-database = { path = "../github_scbot_database" }
github-scbot-logic = { path = "../github_scbot_logic" }
github-scbot-redis = { path = "../github_scbot_redis" }
github-scbot-types = { path = "../github_scbot_types" }

actix-cors = "0.5"
actix-http = "2.2"
actix-service = "1"
actix-web = "3"
actix-web-httpauth = "0.5"
actix-web-prom = "0.5"
futures = "0.3"
hex = "0.4"
regex = "1.4"
rust-crypto = "0.2"
sentry = "0.21"
sentry-actix = { path = "../sentry_actix", features = ["eyre"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
actix-rt = "1"
chrono = { version = "0.4.19", features = ["serde"] }
pretty_assertions = "0.7.2"
