[package]
name = "github-scbot-server"
version = "0.1.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
github-scbot-core = { path = "../github_scbot_core" }
github-scbot-database = { path = "../github_scbot_database" }
github-scbot-logic = { path = "../github_scbot_logic" }
github-scbot-types = { path = "../github_scbot_types" }
actix-rt = "1"
actix-service = "1"
actix-web = "3"
futures = "0.3"
hex = "0.4"
regex = "1.4"
rust-crypto = "0.2"
sentry = { version = "0.21.0", features = ["log"] }
sentry-actix = "0.21.0"
serde_json = "1"
thiserror = "1.0"
tracing = "0.1"
