[package]
name = "prbot-database-pg"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prbot-config = { path = "../prbot-config" }
prbot-database-interface = { path = "../prbot-database-interface" }
prbot-models = { path = "../prbot-models" }

async-trait = { workspace = true }
serde_json = { workspace = true }
sqlx = { version = "0.7.4", features = ["runtime-tokio-native-tls", "postgres"] }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
