[package]
name = "prbot-database-interface"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prbot-crypto = { path = "../prbot-crypto" }
prbot-models = { path = "../prbot-models" }

async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
