[package]
name = "github-scbot-macros"
version = "0.23.0-rc1"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.20"
syn = "1.0.98"
proc-macro2 = { version = "1.0.42", default-features = false }
