@startuml Crates dependencies

class API
class CLI
class Conf
class Crypto
class DB
class Logic
class Redis
class Server
class TUI
class Types
class Utils

API --> Conf
API --> Crypto
API --> Types
API --> Utils

Conf -> Crypto

CLI --> API
CLI --> Conf
CLI --> DB
CLI --> Logic
CLI --> Server
CLI --> TUI
CLI --> Redis
CLI --> Types

DB --> Conf
DB --> Crypto
DB --> Types
DB --> Utils

Logic --> API
Logic --> Conf
Logic --> DB
Logic --> Types
Logic --> Redis

Redis --> Utils

Server --> API
Server --> Conf
Server --> Crypto
Server --> DB
Server --> Logic
Server --> Redis
Server --> Types

TUI --> Conf
TUI --> Types
TUI --> DB

@enduml
