@startuml Schema
class Repository {
    #id: Integer
    name: String
    owner: String
    pr_title_validation_regex: String
    default_needed_reviewers_count: Integer
    default_strategy: String
}
class PullRequest {
    #id: Integer
    *repository_id: Integer
    number: Integer
    name: String
    automerge: Boolean
    step: String
    check_status: String
    status_comment_id: Integer
    qa_status: String
    wip: Boolean
    needed_reviewers_count: Integer
    locked: Boolean
    merged: Boolean
    base_branch: String
    head_branch: String
}
class Review {
    #id: Integer
    *pull_request_id: Integer
    username: String
    state: String
    required: Boolean
}
class MergeRule {
    #id: Integer
    *repository_id: Integer
    base_branch: String
    head_branch: String
    strategy: String
}

Repository *-- PullRequest : has
Repository *-- MergeRule : has
PullRequest *-- Review : has
@enduml
