[package]
name = "github-scbot-database-interface"
version = "0.23.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
github-scbot-domain-models = { path = "../github-scbot-domain-models" }
github-scbot-core = { path = "../github-scbot-core" }
async-trait = "0.1.56"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.37"
tracing = "0.1.35"
