name: Lint, format, build and test

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test-bot
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/prepare
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: checks-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: just fmt-check
    - run: just lint-err
    - run: just build
    - run: just test-cov
      env:
        BOT_DATABASE_PG_URL: postgres://user:pass@localhost:5432/test-bot
        BOT_LOCK_REDIS_ADDRESS: redis://localhost:6379
    - uses: coverallsapp/github-action@master
      with:
        path-to-lcov: lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
