name: Checks

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test-bot
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly-2021-01-27
        components: rustfmt,clippy
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: extractions/setup-just@v1
    - name: Lint, test, build and run
      run: just fmt-check lint-err test build
      env:
        TEST_DATABASE_URL: postgres://user:pass@localhost:5432/test-bot
