[package]
name = "sentry-eyre"
version = "0.1.0"
authors = ["Denis BOURGE <bourge.denis@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
description = """
Sentry integration for eyre.
"""
edition = "2021"

[dependencies]
sentry-backtrace = "0.25.0"
sentry-core = { version = "0.25.0", features = ["client"] }
stable-eyre = "0.2.2"
